name: github_repository_explorer
description: "A Flutter app to explore GitHub repositories with clean architecture"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  http: ^1.1.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  dartz: ^0.10.1
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  mockito: ^5.4.4

  connectivity_plus_platform_interface: any
  hive_test: any
flutter:
  uses-material-design: true
